In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.svm import SVR, SVC
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from xgboost import XGBRegressor, XGBClassifier
!pip install catboost
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor
from catboost import CatBoostRegressor, CatBoostClassifier
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: catboost in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (1.2.8)
Requirement already satisfied: graphviz in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (2.2.6)
Requirement already satisfied: pandas>=0.24 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (2.3.2)
Requirement already satisfied: scipy in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from matplotlib->catboost) (3.2.4)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\varun\anaconda3\envs\ml_env\lib\site-packages (from plotly->catboost) (2.5.0)

In [9]:
df.head()

NameError: name 'df' is not defined

In [10]:
df = pd.read_csv('stud.csv')

In [11]:
df.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [15]:
X = df.drop(columns=['math_score'], axis=1)
y= df['math_score']
X.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 7 columns]

In [19]:
num_features = X.select_dtypes(exclude='object').columns
cat_features = X.select_dtypes(include='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ('onehot', OneHotEncoder(), cat_features),
    ('scaler', StandardScaler(), num_features)
])

In [21]:
X = preprocessor.fit_transform(X)

In [22]:
X.shape

(1000, 19)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 19), (200, 19), (800,), (200,))

In [38]:
def evaluate_model (y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    return mae, mse, rmse, r2

In [42]:
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'ElasticNet Regression': ElasticNet(),
    'Decision Tree Regressor': DecisionTreeRegressor(),
    'Random Forest Regressor': RandomForestRegressor(),
    'SVR': SVR(),
    'KNeighbors Regressor': KNeighborsRegressor(),
    'XGB Regressor': XGBRegressor(),
    'catboost Regressor': CatBoostRegressor(verbose=0),
    'AdaBoost Regressor': AdaBoostRegressor()
    } 
model_list = []
r2_list = [] 

for model_name, model in models.items():
    model.fit(X_train, y_train) # training the model

    # prediction on training data
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # evaluation on training data
    train_mae, train_mse, train_rmse, train_r2 = evaluate_model(y_train, y_train_pred)
    test_mae, test_mse, test_rmse, test_r2 = evaluate_model(y_test, y_test_pred)

    print(f"Model: {model_name}")
    model_list.append(model_name)
    r2_list.append(test_r2)

    print("Model Training Results:")
    print(f"Train MAE: {train_mae}")
    print(f"Train MSE: {train_mse}")
    print(f"Train RMSE: {train_rmse}")
    print(f"Train R2: {train_r2}")

    print("\nModel Testing Results:")
    print(f"Test MAE: {test_mae}")
    print(f"Test MSE: {test_mse}")
    print(f"Test RMSE: {test_rmse}")
    print(f"Test R2: {test_r2}")
    print("-" * 50)
    print("\n")

Model: Linear Regression
Model Training Results:
Train MAE: 4.266711846071957
Train MSE: 28.33487038064859
Train RMSE: 5.323050852720514
Train R2: 0.8743172040139593

Model Testing Results:
Test MAE: 4.21476314247485
Test MSE: 29.095169866715487
Test RMSE: 5.393993869732843
Test R2: 0.8804332983749565
--------------------------------------------------


Model: Ridge Regression
Model Training Results:
Train MAE: 4.264987823725981
Train MSE: 28.33778823308244
Train RMSE: 5.323324922741654
Train R2: 0.8743042615212909

Model Testing Results:
Test MAE: 4.211100688014261
Test MSE: 29.056272192348324
Test RMSE: 5.390387016935642
Test R2: 0.8805931485028737
--------------------------------------------------


Model: Lasso Regression
Model Training Results:
Train MAE: 5.206302661246526
Train MSE: 43.47840400585579
Train RMSE: 6.593815587795566
Train R2: 0.8071462015863456

Model Testing Results:
Test MAE: 5.157881810347763
Test MSE: 42.5064168384116
Test RMSE: 6.519694535667419
Test R2: 0.8253197323627853
--------------------------------------------------


Model: ElasticNet Regression
Model Training Results:
Train MAE: 6.17007012705435
Train MSE: 60.018938128256735
Train RMSE: 7.747189046890281
Train R2: 0.7337786319564656

Model Testing Results:
Test MAE: 6.390111785692222
Test MSE: 63.35941636178532
Test RMSE: 7.959862835613772
Test R2: 0.7396242583916663
--------------------------------------------------


Model: Decision Tree Regressor
Model Training Results:
Train MAE: 0.01875
Train MSE: 0.078125
Train RMSE: 0.2795084971874737
Train R2: 0.9996534669718089

Model Testing Results:
Test MAE: 6.39
Test MSE: 65.41
Test RMSE: 8.087644898238299
Test R2: 0.7311973778080237
--------------------------------------------------


Model: Random Forest Regressor
Model Training Results:
Train MAE: 1.8177229166666669
Train MSE: 5.159361559027779
Train RMSE: 2.2714228049898106
Train R2: 0.9771150184373398

Model Testing Results:
Test MAE: 4.647183333333333
Test MSE: 36.24638069444444
Test RMSE: 6.0204967149268045
Test R2: 0.8510453726397296
--------------------------------------------------


Model: SVR
Model Training Results:
Train MAE: 4.869189452384867
Train MSE: 43.257024268031365
Train RMSE: 6.57700724251018
Train R2: 0.8081281585902299

Model Testing Results:
Test MAE: 5.4015392444969965
Test MSE: 66.04200493745648
Test RMSE: 8.126623218622633
Test R2: 0.7286001513223705
--------------------------------------------------


Model: KNeighbors Regressor
Model Training Results:
Train MAE: 4.516749999999999
Train MSE: 32.57765
Train RMSE: 5.707683417990174
Train R2: 0.8554978341651085

Model Testing Results:
Test MAE: 5.621
Test MSE: 52.6066
Test RMSE: 7.253040741647602
Test R2: 0.7838129945787431
--------------------------------------------------


Model: XGB Regressor
Model Training Results:
Train MAE: 0.687466561794281
Train MSE: 1.0146163702011108
Train RMSE: 1.0072816737145132
Train R2: 0.9954995512962341

Model Testing Results:
Test MAE: 5.057730674743652
Test MSE: 41.90370559692383
Test RMSE: 6.47330716071189
Test R2: 0.8277965784072876
--------------------------------------------------


Model: catboost Regressor
Model Training Results:
Train MAE: 2.405393926779502
Train MSE: 9.257805405523678
Train RMSE: 3.042664195326799
Train R2: 0.9589358676277713

Model Testing Results:
Test MAE: 4.612531714976557
Test MSE: 36.10365799356841
Test RMSE: 6.008631956907363
Test R2: 0.8516318920747058
--------------------------------------------------


Model: AdaBoost Regressor
Model Training Results:
Train MAE: 4.788017056534864
Train MSE: 34.624235690389085
Train RMSE: 5.884236202803987
Train R2: 0.8464199520947958

Model Testing Results:
Test MAE: 4.807046127698104
Test MSE: 37.48190491125215
Test RMSE: 6.122246720873976
Test R2: 0.8459679815793473
--------------------------------------------------

In [43]:
Results = pd.DataFrame({
    "Model":model_list,
    "R^2 Score":r2_list
}

)

In [44]:
Results

                      Model  R^2 Score
0         Linear Regression   0.880433
1          Ridge Regression   0.880593
2          Lasso Regression   0.825320
3     ElasticNet Regression   0.739624
4   Decision Tree Regressor   0.731197
5   Random Forest Regressor   0.851045
6                       SVR   0.728600
7      KNeighbors Regressor   0.783813
8             XGB Regressor   0.827797
9        catboost Regressor   0.851632
10       AdaBoost Regressor   0.845968

In [50]:
Results.sort_values(by="R^2 Score", ascending=False)

                      Model  R^2 Score
1          Ridge Regression   0.880593
0         Linear Regression   0.880433
9        catboost Regressor   0.851632
5   Random Forest Regressor   0.851045
10       AdaBoost Regressor   0.845968
8             XGB Regressor   0.827797
2          Lasso Regression   0.825320
7      KNeighbors Regressor   0.783813
3     ElasticNet Regression   0.739624
4   Decision Tree Regressor   0.731197
6                       SVR   0.728600